language: python
sudo: false

os: linux
dist: trusty

python:
    - "3.6"

branches:
    only:
        - master

# command to install dependencies
install: "pip install -r requirements.txt"

script:
    "python -m pytest -v test/*"
